git:
  remote:
    upstream: 'mongodb/docs-ecosystem'
    tools: 'mongodb/docs-tools'
project:
  name: 'ecosystem'
  tag: 'ecosystem'
  url: 'http://docs.mongodb.org'
  title: "MongoDB Ecosystem"
  branched: false
system:
  tools:
    ref: HEAD
    pinned: false
  make:
    generated:
      - 'sphinx'
      - 'meta'
      - 'push'
      - 'migrations'
      - 'integration'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
  files:
    - 'pdfs.yaml'
    - 'intersphinx.yaml'
    - 'push.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
version:
  release: '2.6.4'
  branch: '2.6'
assets:
  - branch: master
    path: build/docs-tools
    repository: http://github.com/mongodb/docs-tools.git
  - branch: ecosystem
    path: source/images
    repository: http://github.com/mongodb/docs-assets.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
...