source: 'contents'
title: 'MongoDB Ecosystem Documentation'
output: 'MongoDB-Ecosystem.tex'
author: 'MongoDB Documentation Project'
class: 'manual'
tag: 'guide'
---
source: 'meta/google-compute-engine'
title: 'MongoDB and Google Compute Engine'
output: 'MongoDB-Google-Compute-Engine.tex'
author: 'MongoDB Documentation Project'
class: 'howto'
tag: 'guide'
...
